version: '3.8'
services:
  redis:
    container_name: redis_container
    image: redis:7.2.4-alpine
    restart: always
    ports:
        - 6379:6379
    volumes:
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16