### Toggle 0

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "0",
    "interval": "2"
}

### Toggle 1

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "1",
    "interval": "2"
}

### Toggle 2

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "2",
    "interval": "2"
}

### Toggle 3

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "3",
    "interval": "2"
}

### Toggle 4

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "4",
    "interval": "2"
}

### Toggle 5

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "5",
    "interval": "2"
}

### Toggle 6

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "6",
    "interval": "2"
}

### Toggle 7

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "7",
    "interval": "2"
}

### Toggle 8

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "8",
    "interval": "2"
}

### Toggle 9

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "9",
    "interval": "2"
}

### Toggle 10

POST http://127.0.0.1:7001/toggle
content-type: application/json

{
    "mode": "10",
    "interval": "2"
}